
const Table = {
	TABLE_NAME: {
		PRODUCT: "PRODUCT",
		USER: "USER",
		SELLER: "SELLER",
		BRAND: "BRAND",
		VOUCHER: "VOUCHER",
		REF_VOUCHER_PRODUCT: "REF_VOUCHER_PRODUCT",
		CATEGORIES: "CATEGORIES",
		CART: "CART",
	},


};
module.exports = Table;
