
const Table = {
	TABLE_NAME: {
		PRODUCT: "PRODUCT",
		ACCOUNT: "ACCOUNT",
		USER_INFORMATION: "USER_INFORMATION",
		SELLER: "SELLER",
		BRAND: "BRAND",
		VOUCHER: "VOUCHER",
		REF_VOUCHER_PRODUCT: "REF_VOUCHER_PRODUCT",
		CATEGORIES: "CATEGORIES",

	},


};
module.exports = Table;
