
const Table = {
	TABLE_NAME: {
		PRODUCT: "PRODUCT",
		USER: "USER",
		SELLER: "SELLER",
		BRAND: "BRAND",
		VOUCHER: "VOUCHER",
		REF_VOUCHER_PRODUCT: "REF_VOUCHER_PRODUCT",
		CATEGORIES: "CATEGORIES",
		CART: "CART",
		COMMENT: "COMMENT",
		PRODUCT_ORDER: "PRODUCT_ORDER",
		DELIVERY_INFORMATION: "DELIVERY_INFORMATION",
		ORDER_DETAILS: "ORDER_DETAILS",
	},


};
module.exports = Table;
